# DAI Node Installer — Windows
# Run from the repo root in PowerShell:
#   Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass
#   .\install_node.ps1

$ErrorActionPreference = "Stop"

Write-Host ""
Write-Host "  DAI Node Installer" -ForegroundColor Cyan
Write-Host "  Earn tokens by sharing your GPU or CPU for AI inference."
Write-Host ""

# ── Check Python ──────────────────────────────────────────────────────────────
Write-Host "Checking prerequisites..." -ForegroundColor Yellow

$python = $null
foreach ($cmd in @("python", "python3")) {
    try {
        $ver = & $cmd --version 2>&1
        if ($ver -match "Python 3\.(\d+)") {
            $minor = [int]$Matches[1]
            if ($minor -ge 10) { $python = $cmd; break }
        }
    } catch {}
}

if (-not $python) {
    Write-Host "  ERROR: Python 3.10+ is required." -ForegroundColor Red
    Write-Host "  Download from https://python.org/downloads/" -ForegroundColor Red
    exit 1
}
Write-Host "  Python: OK ($(&$python --version))" -ForegroundColor Green

# ── Install dependencies ──────────────────────────────────────────────────────
Write-Host ""
Write-Host "Installing Python dependencies..." -ForegroundColor Yellow
& $python -m pip install -r requirements.txt --quiet
Write-Host "  Dependencies: OK" -ForegroundColor Green

# ── Configure ─────────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "Configuration" -ForegroundColor Yellow
Write-Host "  (Press Enter to accept defaults)"
Write-Host ""

$orchestrator = Read-Host "  Orchestrator URL [ws://localhost:8000/ws/node]"
if (-not $orchestrator) { $orchestrator = "ws://localhost:8000/ws/node" }

$models = Read-Host "  Models to offer, comma-separated [any]"
if (-not $models) { $models = "any" }

$gpu = Read-Host "  Do you have a GPU? (y/n) [n]"
$gpuFlag = if ($gpu -eq "y") { "--gpu" } else { "" }

$wallet = Read-Host "  Wallet address for on-chain rewards (optional, press Enter to skip)"

# ── Write run script ──────────────────────────────────────────────────────────
$walletArg = if ($wallet) { "--wallet $wallet" } else { "" }

$runScript = @"
# Generated by install_node.ps1
python compute/node.py --orchestrator $orchestrator --models $models $gpuFlag $walletArg
"@

Set-Content -Path "run_node.ps1" -Value $runScript

# ── Done ──────────────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "  Setup complete!" -ForegroundColor Green
Write-Host ""
Write-Host "  To start your node:" -ForegroundColor Cyan
Write-Host "    .\run_node.ps1"
Write-Host ""
Write-Host "  For real AI inference, install Ollama (https://ollama.com) and run:"
Write-Host "    python compute/node.py --ollama --auto"
Write-Host ""
