#!/usr/bin/env bash
# DAI Node Installer — Linux / macOS
# Run from the repo root:
#   chmod +x install_node.sh && ./install_node.sh

set -e

GREEN='\033[0;32m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

echo ""
echo -e "  ${CYAN}DAI Node Installer${NC}"
echo "  Earn tokens by sharing your GPU or CPU for AI inference."
echo ""

# ── Check Python ──────────────────────────────────────────────────────────────
echo -e "${YELLOW}Checking prerequisites...${NC}"

PYTHON=""
for cmd in python3 python; do
    if command -v "$cmd" &>/dev/null; then
        ver=$("$cmd" -c "import sys; print(sys.version_info.minor)")
        major=$("$cmd" -c "import sys; print(sys.version_info.major)")
        if [ "$major" -eq 3 ] && [ "$ver" -ge 10 ]; then
            PYTHON="$cmd"
            break
        fi
    fi
done

if [ -z "$PYTHON" ]; then
    echo -e "  ${RED}ERROR: Python 3.10+ is required.${NC}"
    echo "  Install via your package manager or https://python.org/downloads/"
    exit 1
fi
echo -e "  Python: ${GREEN}OK${NC} ($($PYTHON --version))"

# ── Install dependencies ──────────────────────────────────────────────────────
echo ""
echo -e "${YELLOW}Installing Python dependencies...${NC}"
$PYTHON -m pip install -r requirements.txt --quiet
echo -e "  Dependencies: ${GREEN}OK${NC}"

# ── Configure ─────────────────────────────────────────────────────────────────
echo ""
echo -e "${YELLOW}Configuration${NC}"
echo "  (Press Enter to accept defaults)"
echo ""

read -rp "  Orchestrator URL [ws://localhost:8000/ws/node]: " ORCHESTRATOR
ORCHESTRATOR="${ORCHESTRATOR:-ws://localhost:8000/ws/node}"

read -rp "  Models to offer, comma-separated [any]: " MODELS
MODELS="${MODELS:-any}"

read -rp "  Do you have a GPU? (y/n) [n]: " GPU
GPU_FLAG=""
[ "$GPU" = "y" ] && GPU_FLAG="--gpu"

read -rp "  Wallet address for on-chain rewards (optional, Enter to skip): " WALLET
WALLET_ARG=""
[ -n "$WALLET" ] && WALLET_ARG="--wallet $WALLET"

# ── Write run script ──────────────────────────────────────────────────────────
cat > run_node.sh <<EOF
#!/usr/bin/env bash
# Generated by install_node.sh
$PYTHON compute/node.py --orchestrator $ORCHESTRATOR --models $MODELS $GPU_FLAG $WALLET_ARG
EOF
chmod +x run_node.sh

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
echo -e "  ${GREEN}Setup complete!${NC}"
echo ""
echo -e "  To start your node:"
echo -e "    ${CYAN}./run_node.sh${NC}"
echo ""
echo "  For real AI inference, install Ollama (https://ollama.com) and run:"
echo "    $PYTHON compute/node.py --ollama --auto"
echo ""
